//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aughip_installer_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aughip_installer_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string btn_landing_about {
            get {
                return ResourceManager.GetString("btn_landing_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string btn_landing_install {
            get {
                return ResourceManager.GetString("btn_landing_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string btn_landing_licenses {
            get {
                return ResourceManager.GetString("btn_landing_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed!.
        /// </summary>
        public static string DOWNLOAD_FAILED {
            get {
                return ResourceManager.GetString("DOWNLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Hip 0.1.
        /// </summary>
        public static string DOWNLOAD_MODULE_AUGHIP {
            get {
                return ResourceManager.GetString("DOWNLOAD_MODULE_AUGHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual C++ Redist.
        /// </summary>
        public static string DOWNLOAD_MODULE_VCREDIST {
            get {
                return ResourceManager.GetString("DOWNLOAD_MODULE_VCREDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download AugHip! Join the Discord (https://k2vr.tech) for help!.
        /// </summary>
        public static string ERR_DOWNLOAD_FAIL_AUGHIP {
            get {
                return ResourceManager.GetString("ERR_DOWNLOAD_FAIL_AUGHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download VCRedist! Join the Discord (https://k2vr.tech) for help!.
        /// </summary>
        public static string ERR_DOWNLOAD_FAIL_VCREDIST {
            get {
                return ResourceManager.GetString("ERR_DOWNLOAD_FAIL_VCREDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed (Try closing SteamVR).
        /// </summary>
        public static string ERR_INSTALL_FAIL_STEAMVR_RUNNING {
            get {
                return ResourceManager.GetString("ERR_INSTALL_FAIL_STEAMVR_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install Microsoft Visual C++ Redistributable (You might have to manually install it yourself).
        /// </summary>
        public static string ERR_INSTALL_FAIL_VCREDIST_FAILED {
            get {
                return ResourceManager.GetString("ERR_INSTALL_FAIL_VCREDIST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while trying to uninstall. Join our Discord (https://k2vr.tech) for help on manually uninstalling..
        /// </summary>
        public static string ERR_UNINSTALL_FAILED {
            get {
                return ResourceManager.GetString("ERR_UNINSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Augmented Hip.
        /// </summary>
        public static string INSTALL_STATE_INSTALL_AUGHIP {
            get {
                return ResourceManager.GetString("INSTALL_STATE_INSTALL_AUGHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Visual C++ Redistributable.
        /// </summary>
        public static string INSTALL_STATE_INSTALL_VCREDIST {
            get {
                return ResourceManager.GetString("INSTALL_STATE_INSTALL_VCREDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering OpenVR Driver.
        /// </summary>
        public static string INSTALL_STATE_REGISTER_OPENVR {
            get {
                return ResourceManager.GetString("INSTALL_STATE_REGISTER_OPENVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Uninstaller.
        /// </summary>
        public static string INSTALL_STATE_REGISTER_UNINSTALLER {
            get {
                return ResourceManager.GetString("INSTALL_STATE_REGISTER_UNINSTALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed Augmented Hip!.
        /// </summary>
        public static string INSTALL_SUCCESS {
            get {
                return ResourceManager.GetString("INSTALL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install success!.
        /// </summary>
        public static string INSTALL_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("INSTALL_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By proceeding with the installation you agree that this software is provided to you &quot;as is&quot; without any warranty whatsoever. In no event shall the authors of this software be liable for any claim, damages or other liability..
        /// </summary>
        public static string liability_text {
            get {
                return ResourceManager.GetString("liability_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string modal_cancel {
            get {
                return ResourceManager.GetString("modal_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string modal_confirm {
            get {
                return ResourceManager.GetString("modal_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string modal_no {
            get {
                return ResourceManager.GetString("modal_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string modal_ok {
            get {
                return ResourceManager.GetString("modal_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string modal_yes {
            get {
                return ResourceManager.GetString("modal_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer can&apos;t continue if SteamVR is running. Close SteamVR?.
        /// </summary>
        public static string PROMPT_CLOSE_STEAMVR {
            get {
                return ResourceManager.GetString("PROMPT_CLOSE_STEAMVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall Augmented Hip?.
        /// </summary>
        public static string PROMPT_UNINSTALL {
            get {
                return ResourceManager.GetString("PROMPT_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string tab_downloading {
            get {
                return ResourceManager.GetString("tab_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string tab_installing {
            get {
                return ResourceManager.GetString("tab_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string tab_landing {
            get {
                return ResourceManager.GetString("tab_landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled successfully!.
        /// </summary>
        public static string UNINSTALL_SUCCESS {
            get {
                return ResourceManager.GetString("UNINSTALL_SUCCESS", resourceCulture);
            }
        }
    }
}
